# Generated by Django 3.0 on 2021-03-15 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('num_plantas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('hab_desde', models.IntegerField(default=0)),
                ('hab_hasta', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('aforo', models.IntegerField(default=0)),
                ('abierto', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=15)),
                ('fk_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='SalaContigua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_sala_contigua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SalaContigua', to='hotel.Sala')),
                ('fk_sala_orig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SalaOrig', to='hotel.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.IntegerField(default=0)),
                ('fk_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Sala')),
            ],
        ),
    ]
