# Generated by Django 3.0 on 2021-03-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstadoActual',
            new_name='EstadoActualSala',
        ),
        migrations.AddField(
            model_name='planta',
            name='fk_hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
            preserve_default=False,
        ),
    ]
